apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
type: Opaque
data:
  PGHOST: dXNlcmRhdGFiYXNlLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  PGUSER: dXNlcmFkbWlu
  PGPORT: NTQzMg==
  PGDATABASE: dXNlcmRi
  PGPASSWORD: cGFzc3dvcmQyOTch